### PR TITLE
Remove WellCommerce project as it's not open source anymore

### PR DESCRIPTION
**Pull request by tucksaun**
It seems https://github.com/WellCommerce/WellCommerce does not exist anymore.
@adampiotrowski please let me know if this new URL is not correct.

### CODE REVIEW

**Comment by adampiotrowski** [comment]
@tucksaun The software itself is still maintained but not as an open-source project. We are cleaning up our repositories so other subtree splits will be also removed shortly.

**Comment by fabpot** [comment]
So, the right thing to do is to remove the project from here, right?

**Comment by adampiotrowski** [comment]
@fabpot @tucksaun For now, yes. I will let you know when we publish the community version.

**Comment by tucksaun** [comment]
@adampiotrowski ACK.
@fabpot PR updated.

**Pull request merged**
